## Exploring dataset

In [1]:
## Importing the necessary packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
## Loading the dataset and viewing the top 5 rows
df = pd.read_csv("../../data/heart/raw/heart_disease_dataset.csv")
df.head()

,Age,Gender,Cholesterol,Blood Pressure,Heart Rate,Smoking,Alcohol Intake,Exercise Hours,Family History,Diabetes,Obesity,Stress Level,Blood Sugar,Exercise Induced Angina,Chest Pain Type,Heart Disease
0,75,Female,228,119,66,Current,Heavy,1,No,No,Yes,8,119,Yes,Atypical Angina,1
1,48,Male,204,165,62,Current,NaN,5,No,No,No,9,70,Yes,Typical Angina,0
2,53,Male,234,91,67,Never,Heavy,3,Yes,No,Yes,5,196,Yes,Atypical Angina,1
3,69,Female,192,90,72,Current,NaN,4,No,Yes,No,7,107,Yes,Non-anginal Pain,0
4,62,Female,172,163,93,Never,NaN,6,No,Yes,No,2,183,Yes,Asymptomatic,0

In [3]:
## Checking the no. of rows and columns in the dataset
df.shape

(1000, 16)

In [4]:
## Checking the info of the data
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      1000 non-null   int64
 1   Gender                   1000 non-null   str
 2   Cholesterol              1000 non-null   int64
 3   Blood Pressure           1000 non-null   int64
 4   Heart Rate               1000 non-null   int64
 5   Smoking                  1000 non-null   str
 6   Alcohol Intake           660 non-null    str
 7   Exercise Hours           1000 non-null   int64
 8   Family History           1000 non-null   str
 9   Diabetes                 1000 non-null   str
 10  Obesity                  1000 non-null   str
 11  Stress Level             1000 non-null   int64
 12  Blood Sugar              1000 non-null   int64
 13  Exercise Induced Angina  1000 non-null   str
 14  Chest Pain Type          1000 non-null   str
 15  Heart Disease            1000 non-null   int64
dtypes: int64(8), str(8)
memory usage: 125.1 KB

In [11]:
## Checking the no. of the missing values
df.isnull().sum()

Age                        0
Gender                     0
Cholesterol                0
Blood Pressure             0
Heart Rate                 0
Smoking                    0
Alcohol Intake             0
Exercise Hours             0
Family History             0
Diabetes                   0
Obesity                    0
Stress Level               0
Blood Sugar                0
Exercise Induced Angina    0
Chest Pain Type            0
Heart Disease              0
dtype: int64

## Cleaning the dataset

In [6]:
## Checking the unique values of the column 'Alcohol Intake'
df['Alcohol Intake'].unique()

<StringArray>
['Heavy', nan, 'Moderate']
Length: 3, dtype: str

In [7]:
## Filling nan values in the column 'Alcohol Intake'
df['Alcohol Intake'] = df['Alcohol Intake'].fillna('Unknown')
df.head()

,Age,Gender,Cholesterol,Blood Pressure,Heart Rate,Smoking,Alcohol Intake,Exercise Hours,Family History,Diabetes,Obesity,Stress Level,Blood Sugar,Exercise Induced Angina,Chest Pain Type,Heart Disease
0,75,Female,228,119,66,Current,Heavy,1,No,No,Yes,8,119,Yes,Atypical Angina,1
1,48,Male,204,165,62,Current,Unknown,5,No,No,No,9,70,Yes,Typical Angina,0
2,53,Male,234,91,67,Never,Heavy,3,Yes,No,Yes,5,196,Yes,Atypical Angina,1
3,69,Female,192,90,72,Current,Unknown,4,No,Yes,No,7,107,Yes,Non-anginal Pain,0
4,62,Female,172,163,93,Never,Unknown,6,No,Yes,No,2,183,Yes,Asymptomatic,0

## Checking if data is balanced or not

In [8]:
print(f"{df['Gender'].value_counts()}")
print("--------------------------------------------------------------------------")
print(f"{df['Smoking'].value_counts()}")
print("--------------------------------------------------------------------------")
print(f"{df['Alcohol Intake'].value_counts()}")
print("--------------------------------------------------------------------------")
print(f"{df['Family History'].value_counts()}")
print("--------------------------------------------------------------------------")
print(f"{df['Diabetes'].value_counts()}")
print("--------------------------------------------------------------------------")
print(f"{df['Obesity'].value_counts()}")
print("--------------------------------------------------------------------------")
print(f"{df['Exercise Induced Angina'].value_counts()}")
print("--------------------------------------------------------------------------")
print(f"{df['Chest Pain Type'].value_counts()}")
print("--------------------------------------------------------------------------")
print(f"{df['Heart Disease'].value_counts()}")
print("--------------------------------------------------------------------------")

Gender
Female    503
Male      497
Name: count, dtype: int64
--------------------------------------------------------------------------
Smoking
Never      338
Current    336
Former     326
Name: count, dtype: int64
--------------------------------------------------------------------------
Alcohol Intake
Heavy       346
Unknown     340
Moderate    314
Name: count, dtype: int64
--------------------------------------------------------------------------
Family History
No     501
Yes    499
Name: count, dtype: int64
--------------------------------------------------------------------------
Diabetes
Yes    505
No     495
Name: count, dtype: int64
--------------------------------------------------------------------------
Obesity
No     501
Yes    499
Name: count, dtype: int64
--------------------------------------------------------------------------
Exercise Induced Angina
No     528
Yes    472
Name: count, dtype: int64
--------------------------------------------------------------------------
Chest Pain Type
Non-anginal Pain    256
Typical Angina      250
Asymptomatic        248
Atypical Angina     246
Name: count, dtype: int64
--------------------------------------------------------------------------
Heart Disease
0    608
1    392
Name: count, dtype: int64
--------------------------------------------------------------------------

## Converting data into numerical format for the ML model

#### Converting the binary values

In [9]:
## Converting the gender column into the numeric
## Checking the unique values
df['Gender'].unique() # ['Female', 'Male']
## Converting into numeric using map function
gender_map = {'Female':0,'Male':1} 
df['Gender'] = df['Gender'].map(gender_map)
df.head()

,Age,Gender,Cholesterol,Blood Pressure,Heart Rate,Smoking,Alcohol Intake,Exercise Hours,Family History,Diabetes,Obesity,Stress Level,Blood Sugar,Exercise Induced Angina,Chest Pain Type,Heart Disease
0,75,0,228,119,66,Current,Heavy,1,No,No,Yes,8,119,Yes,Atypical Angina,1
1,48,1,204,165,62,Current,Unknown,5,No,No,No,9,70,Yes,Typical Angina,0
2,53,1,234,91,67,Never,Heavy,3,Yes,No,Yes,5,196,Yes,Atypical Angina,1
3,69,0,192,90,72,Current,Unknown,4,No,Yes,No,7,107,Yes,Non-anginal Pain,0
4,62,0,172,163,93,Never,Unknown,6,No,Yes,No,2,183,Yes,Asymptomatic,0

In [10]:
## Converting the rest of the columns with yes/no values into the numeric

## Checking the unique vals
# df['Family History'].unique() # ['No', 'Yes']
# df['Diabetes'].unique() # ['No', 'Yes']
# df['Obesity'].unique() # ['No', 'Yes']
# df['Exercise Induced Angina'].unique() # ['No', 'Yes']

binary_map = {'Yes':1,'No':0}
bin_cols = ['Family History','Diabetes','Obesity','Exercise Induced Angina']
for col in bin_cols:
    df[col] = df[col].map(binary_map)
df.head()

,Age,Gender,Cholesterol,Blood Pressure,Heart Rate,Smoking,Alcohol Intake,Exercise Hours,Family History,Diabetes,Obesity,Stress Level,Blood Sugar,Exercise Induced Angina,Chest Pain Type,Heart Disease
0,75,0,228,119,66,Current,Heavy,1,0,0,1,8,119,1,Atypical Angina,1
1,48,1,204,165,62,Current,Unknown,5,0,0,0,9,70,1,Typical Angina,0
2,53,1,234,91,67,Never,Heavy,3,1,0,1,5,196,1,Atypical Angina,1
3,69,0,192,90,72,Current,Unknown,4,0,1,0,7,107,1,Non-anginal Pain,0
4,62,0,172,163,93,Never,Unknown,6,0,1,0,2,183,1,Asymptomatic,0

#### Converting the one hot encoding values

##### Dividing the data into the training and tesing

In [12]:
from sklearn.model_selection import train_test_split

In [15]:
X = df.drop('Heart Disease',axis=1)
y = df['Heart Disease']

In [16]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.25,random_state=42)

In [18]:
print(f"{X_train['Gender'].value_counts()}")
print("--------------------------------------------------------------------------")
print(f"{X_train['Smoking'].value_counts()}")
print("--------------------------------------------------------------------------")
print(f"{X_train['Alcohol Intake'].value_counts()}")
print("--------------------------------------------------------------------------")
print(f"{X_train['Family History'].value_counts()}")
print("--------------------------------------------------------------------------")
print(f"{X_train['Diabetes'].value_counts()}")
print("--------------------------------------------------------------------------")
print(f"{X_train['Obesity'].value_counts()}")
print("--------------------------------------------------------------------------")
print(f"{X_train['Exercise Induced Angina'].value_counts()}")
print("--------------------------------------------------------------------------")
print(f"{X_train['Chest Pain Type'].value_counts()}")
print("--------------------------------------------------------------------------")

Gender
0    377
1    373
Name: count, dtype: int64
--------------------------------------------------------------------------
Smoking
Never      255
Current    250
Former     245
Name: count, dtype: int64
--------------------------------------------------------------------------
Alcohol Intake
Unknown     256
Heavy       253
Moderate    241
Name: count, dtype: int64
--------------------------------------------------------------------------
Family History
0    378
1    372
Name: count, dtype: int64
--------------------------------------------------------------------------
Diabetes
0    384
1    366
Name: count, dtype: int64
--------------------------------------------------------------------------
Obesity
0    386
1    364
Name: count, dtype: int64
--------------------------------------------------------------------------
Exercise Induced Angina
0    393
1    357
Name: count, dtype: int64
--------------------------------------------------------------------------
Chest Pain Type
Atypical Angina     198
Asymptomatic        190
Typical Angina      183
Non-anginal Pain    179
Name: count, dtype: int64
--------------------------------------------------------------------------

In [19]:
print(f"{X_test['Gender'].value_counts()}")
print("--------------------------------------------------------------------------")
print(f"{X_test['Smoking'].value_counts()}")
print("--------------------------------------------------------------------------")
print(f"{X_test['Alcohol Intake'].value_counts()}")
print("--------------------------------------------------------------------------")
print(f"{X_test['Family History'].value_counts()}")
print("--------------------------------------------------------------------------")
print(f"{X_test['Diabetes'].value_counts()}")
print("--------------------------------------------------------------------------")
print(f"{X_test['Obesity'].value_counts()}")
print("--------------------------------------------------------------------------")
print(f"{X_test['Exercise Induced Angina'].value_counts()}")
print("--------------------------------------------------------------------------")
print(f"{X_test['Chest Pain Type'].value_counts()}")
print("--------------------------------------------------------------------------")

Gender
0    126
1    124
Name: count, dtype: int64
--------------------------------------------------------------------------
Smoking
Current    86
Never      83
Former     81
Name: count, dtype: int64
--------------------------------------------------------------------------
Alcohol Intake
Heavy       93
Unknown     84
Moderate    73
Name: count, dtype: int64
--------------------------------------------------------------------------
Family History
1    127
0    123
Name: count, dtype: int64
--------------------------------------------------------------------------
Diabetes
1    139
0    111
Name: count, dtype: int64
--------------------------------------------------------------------------
Obesity
1    135
0    115
Name: count, dtype: int64
--------------------------------------------------------------------------
Exercise Induced Angina
0    135
1    115
Name: count, dtype: int64
--------------------------------------------------------------------------
Chest Pain Type
Non-anginal Pain    77
Typical Angina      67
Asymptomatic        58
Atypical Angina     48
Name: count, dtype: int64
--------------------------------------------------------------------------

##### Applying the encoder on the train dataset

In [20]:
from sklearn.preprocessing import OneHotEncoder

In [24]:
## Checking the unique vals
# df['Smoking'].unique() # ['Current', 'Never', 'Former']
# df['Alcohol Intake'].unique() # ['Heavy', 'Unknown', 'Moderate']
# df['Chest Pain Type'].unique() # ['Atypical Angina', 'Typical Angina', 'Non-anginal Pain', 'Asymptomatic']

one_hot_cols = ['Smoking','Alcohol Intake','Chest Pain Type']

## creaeting the encoder object
one_hot_encoder = OneHotEncoder(drop='first',sparse_output=False,handle_unknown='ignore')

## fitting the encoder on the train data
one_hot_encoder.fit(X_train[one_hot_cols])

OneHotEncoder(drop='first', handle_unknown='ignore', sparse_output=False)

In [26]:
## Transforming the data according to the one hot encoder
X_train_encoded = one_hot_encoder.transform(X_train[one_hot_cols])
X_test_encoded = one_hot_encoder.transform(X_test[one_hot_cols])

## Converting to the dataframe
encoded_cols = one_hot_encoder.get_feature_names_out()

X_train_encoded_df = pd.DataFrame(X_train_encoded,columns=encoded_cols,index=X_train.index)
X_test_encoded_df = pd.DataFrame(X_test_encoded,columns=encoded_cols,index=X_test.index)

In [27]:
## Merging everything into the one df of X_train and X_test
X_train = X_train.drop(one_hot_cols,axis=1)
X_test = X_test.drop(one_hot_cols,axis=1)

X_train = pd.concat([X_train,X_train_encoded_df],axis=1)
X_test = pd.concat([X_test,X_test_encoded_df],axis=1)

#### Saving encoder

In [32]:
import joblib
joblib.dump(one_hot_encoder,'../../models/heart/one_hot_encoder.pkl')

['../../models/heart/one_hot_encoder.pkl']

## Scaling the numerical data for the ML model

In [36]:
from sklearn.preprocessing import StandardScaler

In [37]:
num_cols = ['Age','Cholesterol','Blood Pressure','Heart Rate','Exercise Hours','Stress Level','Blood Sugar']

## creating the scaler object
standard_scaler = StandardScaler()

## fitting the scaler on the train data
standard_scaler.fit(X_train[num_cols])

StandardScaler()

In [38]:
## Transforming and saving the data according to the scaler
X_train[num_cols] = standard_scaler.transform(X_train[num_cols])
X_test[num_cols] = standard_scaler.transform(X_test[num_cols])

#### Save scaler

In [42]:
import joblib
joblib.dump(standard_scaler,'../../models/heart/standard_scaler.pkl')

['../../models/heart/standard_scaler.pkl']

## Saving the training and testing datasets

In [51]:
X_train.to_csv("../../data/heart/processed/X_train.csv",index=False)
X_test.to_csv("../../data/heart/processed/X_test.csv",index=False)
y_train.to_csv("../../data/heart/processed/y_train.csv",index=False)
y_test.to_csv("../../data/heart/processed/y_test.csv",index=False)