## Exploring dataset

In [1]:
## Importing the necessary packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
## Loading the dataset and viewing the top 5 rows
df = pd.read_csv("../../../data/heart/raw/new_dataset_cleveland/Cleavland.csv")
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0

In [3]:
## Checking the no. of rows and columns in the dataset
df.shape

(303, 14)

In [4]:
## Checking the info of the data
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    float64
 1   sex       303 non-null    float64
 2   cp        303 non-null    float64
 3   trestbps  303 non-null    float64
 4   chol      303 non-null    float64
 5   fbs       303 non-null    float64
 6   restecg   303 non-null    float64
 7   thalach   303 non-null    float64
 8   exang     303 non-null    float64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    float64
 11  ca        303 non-null    str
 12  thal      303 non-null    str
 13  target    303 non-null    int64
dtypes: float64(11), int64(1), str(2)
memory usage: 33.3 KB

In [5]:
## Checking the no. of the missing values
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [6]:
df["target"] = df["target"].apply(lambda x: 0 if x == 0 else 1)

In [9]:
df.replace("?",np.nan,inplace=True)
df.dropna(inplace=True)
df.shape

(297, 14)

## Checking if data is balanced or not

In [10]:
print(f"{df['sex'].value_counts()}")
print("--------------------------------------------------------------------------")
print(f"{df['cp'].value_counts()}")
print("--------------------------------------------------------------------------")
print(f"{df['fbs'].value_counts()}") # diabetic (1:yes , 0:no)
print("--------------------------------------------------------------------------")
print(f"{df['restecg'].value_counts()}")
print("--------------------------------------------------------------------------")
print(f"{df['exang'].value_counts()}") # exercise induced angina (1 = yes; 0 = no)
print("--------------------------------------------------------------------------")
print(f"{df['slope'].value_counts()}") #  -- Value 1: upsloping -- Value 2: flat -- Value 3: downsloping
print("--------------------------------------------------------------------------")
print(f"{df['ca'].value_counts()}")
print("--------------------------------------------------------------------------")
print(f"{df['thal'].value_counts()}") # 3 = normal; 6 = fixed defect; 7 = reversable defect
print("--------------------------------------------------------------------------")
print(f"{df['target'].value_counts()}")
print("--------------------------------------------------------------------------")

sex
1.0    201
0.0     96
Name: count, dtype: int64
--------------------------------------------------------------------------
cp
4.0    142
3.0     83
2.0     49
1.0     23
Name: count, dtype: int64
--------------------------------------------------------------------------
fbs
0.0    254
1.0     43
Name: count, dtype: int64
--------------------------------------------------------------------------
restecg
0.0    147
2.0    146
1.0      4
Name: count, dtype: int64
--------------------------------------------------------------------------
exang
0.0    200
1.0     97
Name: count, dtype: int64
--------------------------------------------------------------------------
slope
1.0    139
2.0    137
3.0     21
Name: count, dtype: int64
--------------------------------------------------------------------------
ca
0.0    174
1.0     65
2.0     38
3.0     20
Name: count, dtype: int64
--------------------------------------------------------------------------
thal
3.0    164
7.0    115
6.0     18
Name: count, dtype: int64
--------------------------------------------------------------------------
target
0    160
1    137
Name: count, dtype: int64
--------------------------------------------------------------------------

## Converting data into numerical format for the ML model

In [13]:
df['ca'] = df['ca'].apply(pd.to_numeric)
df['thal'] = df['thal'].apply(pd.to_numeric)
df.info()

<class 'pandas.DataFrame'>
Index: 297 entries, 0 to 301
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       297 non-null    float64
 1   sex       297 non-null    float64
 2   cp        297 non-null    float64
 3   trestbps  297 non-null    float64
 4   chol      297 non-null    float64
 5   fbs       297 non-null    float64
 6   restecg   297 non-null    float64
 7   thalach   297 non-null    float64
 8   exang     297 non-null    float64
 9   oldpeak   297 non-null    float64
 10  slope     297 non-null    float64
 11  ca        297 non-null    float64
 12  thal      297 non-null    float64
 13  target    297 non-null    int64
dtypes: float64(13), int64(1)
memory usage: 34.8 KB

## Dividing cols into numerical , binary and encoding

In [14]:
num_cols = ['age','trestbps','chol','thalach','oldpeak','ca']
binary_cols = ['fbs','exang']
categorical_cols = ['cp','restecg','slope','thal']

## Making maps for columns

In [15]:
## binary_map (yes:1,no:0)
binary_map = {"Yes":1 , "No":0}
## for gender (1 = male; 0 = female)
gender_map = {"Male":1,"Female":0}
## for chest pain -- Value 1: typical angina -- Value 2: atypical angina -- Value 3: non-anginal pain -- Value 4: asymptomatic
chest_pain_map = {"Typical Angina":1 , "Atypical Angina": 2 , "Non-anginal Pain": 3 , "Asymptomatic": 4}
# for restecg -- Value 0: normal -- Value 1: having ST-T wave abnormality (T wave inversions and/or ST elevation or depression of > 0.05 mV) -- Value 2: showing probable or definite left ventricular hypertrophy by Estes' criteria
restecg_map = {"Normal": 0 , "ST-T Wave Abnormality": 1 , "Left Ventricular Hypertrophy": 2}
## slope -- Value 1: upsloping -- Value 2: flat -- Value 3: downsloping
slope_map = {"Upsloping": 1 , "Flat": 2 , "Downsloping": 3}
## thal 3 = normal; 6 = fixed defect; 7 = reversable defect
thal_map = {"Normal": 3 , "Fixed Defect": 6 , "Reversible Defect": 7}

## Dividing the data into train and test

In [16]:
from sklearn.model_selection import train_test_split

X = df.iloc[:,:-1]
y = df.iloc[:,-1]

X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.20,random_state=42)

## Encoding data

In [20]:
from sklearn.preprocessing import OneHotEncoder

one_hot_encoder = OneHotEncoder(drop='first',sparse_output=False,handle_unknown='ignore')
one_hot_encoder.fit(X_train[categorical_cols])

X_train_encoded = one_hot_encoder.transform(X_train[categorical_cols])
X_test_encoded = one_hot_encoder.transform(X_test[categorical_cols])
encoded_cols = one_hot_encoder.get_feature_names_out()
X_train_encoded_df = pd.DataFrame(X_train_encoded,columns=encoded_cols,index=X_train.index)
X_test_encoded_df = pd.DataFrame(X_test_encoded,columns=encoded_cols,index=X_test.index)

X_train = X_train.drop(categorical_cols,axis=1)
X_test = X_test.drop(categorical_cols,axis=1)
X_train = pd.concat([X_train,X_train_encoded_df],axis=1)
X_test = pd.concat([X_test,X_test_encoded_df],axis=1)

X_train.head()

,age,sex,trestbps,chol,fbs,thalach,exang,oldpeak,ca,cp_2.0,cp_3.0,cp_4.0,restecg_1.0,restecg_2.0,slope_2.0,slope_3.0,thal_6.0,thal_7.0
277,39.0,0.0,138.0,220.0,0.0,152.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
262,60.0,0.0,150.0,240.0,0.0,171.0,0.0,0.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,69.0,0.0,140.0,239.0,0.0,151.0,0.0,1.8,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,58.0,1.0,120.0,284.0,0.0,160.0,0.0,1.8,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
281,47.0,1.0,130.0,253.0,0.0,179.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Saving encoder

In [21]:
import joblib
joblib.dump(one_hot_encoder,'../../../models/heart/new_models/new_one_hot_encoder.pkl')

['../../../models/heart/new_models/new_one_hot_encoder.pkl']

## Scaling data

In [22]:
from sklearn.preprocessing import StandardScaler

standard_scaler = StandardScaler()
standard_scaler.fit(X_train[num_cols])

X_train[num_cols] = standard_scaler.transform(X_train[num_cols])
X_test[num_cols] = standard_scaler.transform(X_test[num_cols])

X_train.head()

,age,sex,trestbps,chol,fbs,thalach,exang,oldpeak,ca,cp_2.0,cp_3.0,cp_4.0,restecg_1.0,restecg_2.0,slope_2.0,slope_3.0,thal_6.0,thal_7.0
277,-1.741679,0.0,0.319284,-0.544213,0.0,0.151798,0.0,-0.915041,-0.720577,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
262,0.601114,0.0,0.985981,-0.161771,0.0,0.971399,0.0,-0.121634,-0.720577,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,1.605169,0.0,0.430400,-0.180893,0.0,0.108661,0.0,0.671774,1.387777,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,0.377991,1.0,-0.680763,0.679601,0.0,0.496893,0.0,0.671774,-0.720577,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
281,-0.849186,1.0,-0.125182,0.086816,0.0,1.316494,0.0,-0.915041,-0.720577,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Saving scaler

In [23]:
import joblib
joblib.dump(standard_scaler,'../../../models/heart/new_models/new_standard_scaler.pkl')

['../../../models/heart/new_models/new_standard_scaler.pkl']

## Saving test and train datasets

In [24]:
X_train.to_csv("../../../data/heart/processed/new_dataset_cleveland/X_train.csv",index=False)
X_test.to_csv("../../../data/heart/processed/new_dataset_cleveland/X_test.csv",index=False)
y_train.to_csv("../../../data/heart/processed/new_dataset_cleveland/y_train.csv",index=False)
y_test.to_csv("../../../data/heart/processed/new_dataset_cleveland/y_test.csv",index=False)